#!/bin/bash

ls - List the files in the working directory

ls /bin	- List the files in the /bin directory (or any other directory we care to specify)

ls -l - List the files in the working directory in long format

ls -l /etc /bin - List the files in the /bin directory and the /etc directory in long format

ls -la .. - List all files (even ones with names beginning with a period character, which are normally hidden) in the parent of the working directory in long format)
