#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

HOURS=0
while [ $HOURS -lt 12 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 59 ]
    do
        echo $MINUTES
	((MINUTES+=1))
    done
    ((HOURS+=1))
done
